dist: trusty
language: csharp
mono: none
dotnet: 2.1
git:
  depth: 9999999
branches:
  only:
  - develop
  - master
  - "/^feature\\/.*$/"
before_install:
- echo 'Installing GitVersion...'
- dotnet tool install -g GitVersion.Tool --version '4.0.1-*'
- echo Cleaning up NuGet lock files...
- rm -rf /tmp/NuGetScratch/lock
script:
- export PATH="$PATH:$HOME/.dotnet/tools"
- "/bin/bash ./build-ci.sh"
- "/bin/bash ./publish-ci.sh"
env:
  global:
  # MyGet
  - secure: "UlR2gj0Z/vktTZ0YGQ6InYUDA5Z1+zcxHUapgjRjPCynNYE0xoNycPBl97nuR+ZLdiGFBe1kmVOIZdv1GhMEV6og5rp2F8G5Flk3EZ7uDFjM0TcowsOWP/pddpipl4LetS13WgDsV7kEMN6PQI7vwxPKV09X/W8YFSosB155e/LbJJcF9jfQ2D0BWoSgYj0KxmPVRyOc31SMiRo3JHfbSaeszThVtDRu1TaZaJiuOZOICmnse9Kjxw4Cjd2twGImpm6Ha9YZs6xDhtU3nsbWD+98zfhM2DoewjxsUAePztEQnW7BTmyKBHdM4FH6WdCBxOTG7TFgRov+9cGM8YUMYNpFINlWSbwmL3y8eapxWgfA7KPaqyigUs6n/ZkUbOgvlOfEw++srGt+SfhGpxztilPBtxZFDS79U4QuLfGNdc+Wq4GJEm2CEPkiStPOHq7SnidjZ9Iz0POnkSxIDEjL2WhRaxpPTe45gAZyiHtZ0F5eZHwBQmMCr3yiBMvSqqyu/OgOYspSLHu4ktInd26vKaPMGSFKMAwJBmD6Xv8gcRt+Y2saFP7JV+uONpod1WnASbllu/mGdRBLHsvTVdT84i3BjPX34eTnHYkoTBe26gum9vE6BAJ2GqDbSMSWy9SQSKzcbix0KS/R6ivOVi946JXKjhEsSoAw5Mee523CViA="
  # NuGet
  - secure: "CYx8scImtV+Otvet3+HJ798YnkEXViGgD2yU5/VHg2jIBAP8A02SYnqBXJ7GvWYigeN89ySn3bIa5Q44DWdDB8gk7r6K2EGKXNNxk6VBOibzXc45/74qjPwN4X2KfWPzwh/ymyCzv5+uLzxJnv+kf/uJh0PjGLAdwcDjO0idmomqAgXMQphxmrN4ILHqetvq6ecZb0Sd5IeH7Eg3o+T0dhEhFoqCRdOPBHUdg4eTPf4POszv4GW4Ye6lGVWksjislCOf1UGxLC9b2b+gRrMfoJZSeEvaSLJBxdb8s6fkB7/lVHXOFtExCAwK6xGGNBhrnDsWNW1cfaEAs8KNwAO2Zr4sst55wuzB8iksS9VWz9w0pE0JSHDL0z7gg+6C+Jk66d4F9teJ7Ujvin4b1s5J8VXBrsDFqS6CjQRNc4GUvZIisXKl1UkCX6oXeAViGMlTw5PNBtsPdXMdu6rc2Mt8Q/Hym1KxVWHnTeP11SBsXXVb9jd2Ikl1FXxVVhKroHrG/ERegqHXaDEwqRB5lm7FJIYGYsCrpUPwdItxcyoB05mVAYjKBiaiBSO4331cNgUYLjz8kbIO29og0ZlUq/svdl/YD6XAdWP8nsNydfi2Crzm//vFdASlrhNeq1MVwQTEcNwJ52wZF/DBMNgzxuETvp2DPNzUTHI+YyOE036RHDg="
