dist: trusty
language: csharp

mono: none

# Needed by GitVersion
git:
  depth: 9999999

branches:
  only:
    - develop
    - master
    # Feature branches
    - /^feature\/.*$/

before_install:
  - echo 'Installing .NET Core...'
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - sudo apt-get -qq update
  - sudo apt-get install -y curl
  - sudo curl -L -o /tmp/packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i /tmp/packages-microsoft-prod.deb
  - sudo apt-get -qq update
  - sudo apt-get install dotnet-sdk-2.1
  - sudo dotnet tool install -g GitVersion.Tool --version 4.0.1-*

script:
  - /bin/bash ./build-ci.sh
  - /bin/bash ./publish-ci.sh

env:
  global:
    - secure: "ZIwB05HxjhMMfNcziZ+hn+nnljsUSK2OS0+mgpp6lJgknaJymKmgb76UelyGk4SGGiunxErsgp4sYuqtc9G4a6aJZVqJkiyxWjsUKEz7tTlVzt4jPQix/B5xpTTLU7yNemuZ3/o92YIcmSrurDMvpU09+x2SwjQgPlCkVZsshcWFLvBEpA955yS/Ks/+HPfRf+IxM2KKSoKn4nUvVp/KAtr0PlIvlcRWfuisHok9M2tzuI+1m+FyqyD7xTHFGCkIRGDu4xlG6Io6VuCdxBrWcPWwLxdOWfYTKPZhcim/L6b4pTfhwDvoIPEI+INUjds+H47qasys4ATtJ9kF4qDXX8MncM/Ws009RyVZYpWn4HjtVnXiH6XQ0/nlG2K3JEI8sF2UxLAAJb4IaPnTmeg4460gRewWGXCtAvdOjvnnfJDmhsQvhhu8WswRfLuLP05k++aoyYgFI0HjggdUwaiGtqAZH4QF6ZctnBGEdLEBz9YlOBVu+l5lDfkbVF327IRb4DClZBOLhUeOv4hVaRZEBCWLuyaHH26yz7GFwXYcDfY2kINg+7N+04aUNnTFSj8NzID1SdgrWacp6rmECkq12cYAHYWhJaGc+76Xp6jS2k1zfFXeY7rZsEA8JlTwrAkfzK9M3DFhDWbqiIuykNgzdwoyqayLx+pHb14baKD6WaM="
    - secure: "Rc+7dCJfL67YWwRgEm5ema+wm8hXlXDjCrJYDXpNqXQuLD/Q8vlwQojQv/tjKDb+iqlGRvqOrfdvueDlLEmAzHkr2VuSKUfSTdR8lIZMz/P/9bsLDXxnfGgDfdzIi1p4MPJnahYPuZWA1o0C5lxCIRBhakwZFzYPkzPyGWSLIdFKpSnZ9pjNtSc2bDvfShzKvRxSUOBjCyf2REZsYtj/VbByp/L5HsJgaPCtAZ0AC6H+lyuriaBFf6rQL0/3ZcIM/co0ViPqMA6R84/ewJsdME5Jk6C+0/tR/WBIb6pkRaN9AHYCOzsyMq0TBE9s6HUhamxLKb2hJHBQDeVzzBpqm6Ve2nK/djRma/k0QwrOr0XpxEq4iqRdEnDAdWpq6fJme7LeqJPLQB2qXwPNV8eZD/IDK8X8pWrLG7dqJ/ORsis34xEgm77asKIlGSiykQSpQM4KrjSWgOt5Uk5jNPGYVQ34x/vgTZJTLzJuQC5G0TB5VUxPDwgD/tg9GH0RJbprmVjSFDCedt0afv55eM4vw7ssIsiFUegn3Suk9nqFeGp4vk40m7OQ/cXAdCBaBKpYLTT1Xa31uY4lBt4OV6g06QxIDkH00J4p+xIPo4DeA8iQPhYyR1fY/pLI31FnFtU9n9gzeZEeBLoXV/VPWQjnlHhfkuEvVY8+cpow4EOnOvc="
