dist: trusty
language: csharp
mono: none
dotnet: 2.1
git:
  depth: 9999999
branches:
  only:
  - develop
  - master
  - "/^feature\\/.*$/"
before_install:
- echo 'Installing GitVersion...'
- dotnet tool install -g GitVersion.Tool --version '4.0.1-*'
- echo Cleaning up NuGet lock files...
- rm -rf /tmp/NuGetScratch/lock
script:
- export PATH="$PATH:$HOME/.dotnet/tools"
- "/bin/bash ./build-ci.sh"
- "/bin/bash ./publish-ci.sh"
env:
  global:
  # MyGet
  - secure: cJ/t6u0DSCFiaqBR8ka4fF/baXNvrsbFAvXuTBZkmIuBHucBHk9yMVSw8PNKVjmQ1DihnVfyFW3drfbi2oFoGFmeC+b5Hk95DuRX71vMlak8Zd+SxtkM6dxUtuyCY+kJg1VvI1+xTMPum7wMXc0kJFH2yMebkHN1rcUDKkqVrF9x86uYOnQiv6TAr3IB+Fuprx6cKZZx4CHNFnwDcX8ysJrkWEyYNpk/MaE8yRQffGBzTym2z8ZIMU5fl9pftlHf5H8TV6m/ymvBAcwxgKYmrZZQVKF5OcBed2yWbkCzFGNcoi1dkywSb2U8DLCd5OxBvOUBdu/dg3LepOdrp1DfQaAKqrt/P6MXu1ePZpc0S9ya4eZqcLl4tngAhvwhUzEPtDnp+DvCRHYsFo+VqNhRfQ+OT5XcGr3ifh/MBr8C4ufnOgEI14/6bt1jZiUWizhzirNFQETjIZH1hf5nIKY/ou7D+gf6Vxu090wEmDEJRahsuKPuChreDNci22OrWm9IORpGA34ukFapHyuVmqnrdL3xZddMk5sFoPBunZxTTVy2UBs6z7ryUQt1wp/sr6EZDHF37H7XWyawbnZyEUhswT/68Kc8Rs7ANtg+UjWbFRqfiPArLxNW9DvGB2j+YQX/xMjTjf9c+eaV3yiEhCIu/bqWP3kyu90a4XnwmSvjM3o=
  # NuGet
  - secure: O543YcYNXOeBSn7wZAdp/dXBZgOdawfKRzO6+OnsnVEizm+NrKbEY3HFtZJBpWxTKvQCwKFSWLWom4aa00zXbm+7uXJcdYlW6MbpWXVdKrhIzi+Dj9fjgQQzwBclT/dOE0PlpAjEJBrMA+sDIIsvrOYWgmuCPeqkFj7Ww06XAzbBUxvxNdaH14ahdJ4IptNwD4W4rObDDeXaHNo521LYNWeCO2SmmzjjCZpGD+ydqVCYi6WwmmLbHnGEFct+8e/Y2p0nDS5hYkiyWU1oHYS5Ft3Io40YzrZhJI2rFcaWrK3vrfYfmf0gC4GL4U8JXqpSPQJW/Pj8h0/ZO/kL3kN/3SNVPFFa7PiqxI70JcTtAd+nMLL3WWGyDAFAe7nxactSAKNqEoeewsWZI9cBu0ZZSrwYTXzRE9w+TsVFAhjKqtZaUbiShLAl/4NsSmZ7wp59FYP6ETRGuNWzVxq10toBl7guEllq+QHkiK4lY9dXQptXHX2VqlqEkqf2s6VUD5VQwnADltMBQAQFQFy5qX6+P9CVEtzTWVkuesEde49JIDVNcHQizIU4Loroyn6PQAIudU8l2Kuo9caD2qsNoLVVGVwHgieeh2gvKbJNCxgT1I5uJoFu4aHH7e4MQwXu3FC8EWfk9669SdC1s5EiS1qdir4NPrtmbHAB9cf8p3CEprI=
