dist: trusty
language: csharp
mono: none
dotnet: 2.1
git:
  depth: 9999999
branches:
  only:
  - develop
  - master
  - "/^feature\\/.*$/"
before_install:
- echo 'Installing GitVersion...'
- dotnet tool install -g GitVersion.Tool --version '4.0.1-*'
- echo Cleaning up NuGet lock files...
- rm -rf /tmp/NuGetScratch/lock
script:
- export PATH="$PATH:$HOME/.dotnet/tools"
- "/bin/bash ./build-ci.sh"
- "/bin/bash ./publish-ci.sh"
env:
  global:
  # MyGet
  - secure: "U2gPeTQ9NzYGzeJnWRUSDfmk7dIlxQrTQPrwW/vlnjo8J9H4E6zmys0P9JoC4iCYwGC9PYFY33QByXOTYw9IXcJYiNX/wIdsllcQOPd89P2jKlB3KJv3a0QRavLiVBmKeA27Frxf3vJuAlwu6zkXoHz2u8eRoO7uGDeQFUYE/Nc1Zm2sXdzUzifok11vuqAyUTx0eWmYMuOG/el/b+/WIXUx7qhACpvPMFOCSWBYhWJD2EJNDCRiFS3k3/EsMu4ZTjaU1I+YMifIcdK6BX8Olucg8fmxciOA2gBDocF6jiyhxJDVHcnCbuwBRbKxKISu1uqBGQU66aGJXNve+J9VFtObOtDXOxBJsBq2xMAcHC+U558EeZ1LuSP5mGgZmanCjfeu+9PdokVmmLkAbFCwEhYxngGeaWHFHX8aPEnspNuO1uqT858fJnrx+qiPiU/nnqc0Mp6eQzeS1AH2K7/B0xnRcQtbnINaX+lS9CjGuD57VVyrhq4C/ssYPB7SWOTQIHN+8iFQfKk/LgYSU5CDu5bO905NYMn5WCIqsf80w7GrusY0Bn380apcODpb8/ns23dQtZNG0rhmeBgBSceBUKCtpndLsLHsFGKcpQdg/ARWd1WXppzL0EWQHPPq57fXBt0Qze9W6U573EGBQgIwub6/5rGM0T61J6iZnzPNhUE="
  # NuGet
  - secure: "EMgHzB5hLrq7Mk7u8h1ujKwwF7Wh73aXgvteo6YBjoEOAz6O41evAahY509trWzcfR2Rqrrulymjzcm4WsJWydL/IOS1IYtxOIr9VNcXvZUEG3TGOZqd+HEEX2BPQr6nmNWz/U5wlh7rGaIHrFQIjiy9hMcEtQ0leHQ5BChL2cQkxsSvDylWT/BUuv9+ksdD9BnWov7g2Y+rxa5FOe7/mkT6leE5LTFY66FyauhkUzGl/ZYy5aq/pmJkikYQQn8NNLEHWxCtmLYiseyhAk0Dwu6qaBcsoKvQsZnFAxKmSC9d9GZmEMrI0Q4D5OWYrVIcwVFjfGffWQ2SRUEHKa3s0fkik8fKB9Kf6Z/ug6ajyzfXL6iz8qGumjeVtZpCXNoqk54J/oX6psXiAA4me26TXmKl/g3YBkMNF6J+zAg/xKTu9+aNN9+Kj+nAvWtEfA9ozuiOUzVd4834YmE1eB+dKRq/KT50Ptrr8JA3vuHb7p6hxkWRcMIUKeuI2W6LJus5DrjzUfZh4v7q8huFK9ekkd4ykXfsh3LuEC5uNm/l9GSq1W4//UAH5k2Nlc8oCk1bWqSxBrZfEnOu+/xyhVKPToBKvW/33XmaVarsYouQOt7B23qziMchtEb0IyZPNSqc1wKjWbTX2tw3nQsKUVqVqjyymYJabkJfJpt+pArpDbw="
